### ISSUE TITLE
The case breaks if another case is opened at the same time

### ISSUE THREAD

**Issue by Progressier** [Jodexx/DonateCase#44]
### How to reproduce:
1. Place two cases as two identical blocks in front of you;
2. Open case №1, the opening animation will start playing;
3. While the animation of opening the first case is playing, open case №2.

### Actual behavior:
The animation of the first case seems to jump to the second case, the second case opens, and the first one cannot be opened now - the message "Wait, the case opens" appears

### Expected behavior:
The cases are opened in parallel, first case №1, then case №2. After opening both cases, access to them is not blocked

Plugin version: 2.2.3.7
Server: Paper 1.21

@Jodexx pls help

**Comment by Jodexx** [comment]
> ### How to reproduce:
> 1. Place two cases as two identical blocks in front of you;
> 2. Open case №1, the opening animation will start playing;
> 3. While the animation of opening the first case is playing, open case №2.
> 
> ### Actual behavior:
> The animation of the first case seems to jump to the second case, the second case opens, and the first one cannot be opened now - the message "Wait, the case opens" appears
> 
> ### Expected behavior:
> The cases are opened in parallel, first case №1, then case №2. After opening both cases, access to them is not blocked
> 
> Plugin version: 2.2.3.7
> Server: Paper 1.21
> 
> @Jodexx pls help

Hello! This error fixes in newest versions.

**Comment by Progressier** [comment]
> > ### How to reproduce:
> > 
> > 1. Place two cases as two identical blocks in front of you;
> > 2. Open case №1, the opening animation will start playing;
> > 3. While the animation of opening the first case is playing, open case №2.
> > 
> > ### Actual behavior:
> > The animation of the first case seems to jump to the second case, the second case opens, and the first one cannot be opened now - the message "Wait, the case opens" appears
> > ### Expected behavior:
> > The cases are opened in parallel, first case №1, then case №2. After opening both cases, access to them is not blocked
> > Plugin version: 2.2.3.7
> > Server: Paper 1.21
> > @Jodexx pls help
> 
> Hello! This error fixes in newest versions.

Thanks!
