### ISSUE TITLE
Звук відкриття кейсу

### ISSUE THREAD

**Issue by ShvaGrun** [Jodexx/DonateCase#47]
Якщо гравець відкриває кейс на спавні, то його чують абсолютно всі, хто перебуває у тому ж світі

**Comment by Jodexx** [comment]
Hello, thank you for notification.

**Comment by Jodexx** [comment]
https://github.com/Jodexx/DonateCase/commit/ee039a8c69602b4d1dca19e7feb5d975b2afb471
