### ISSUE TITLE
получить кейсы игрока

### ISSUE THREAD

**Issue by seven7sas** [Jodexx/DonateCase#56]
Здравствуйте, я бы хотел узнать можно ли получить все кейсы игрока которые у него находятся

**Comment by Jodexx** [comment]
> Здравствуйте, я бы хотел узнать можно ли получить все кейсы игрока которые у него находятся

Здравствуйте. Если речь идёт о плейсхолдере, то можно с помощью %donatecase_keys%, он будет выводить общее количество ключей от всех кейсов.

Говоря про код, то в таком случае нужно делать итерацию по всех существующих кейсах. Для начала получить DCAPIBukkit - [ссылка на страницу википедии](https://wiki.jodexindustries.xyz/ru/docs/2.0.0/DonateCase/API/Spigot/implementing)

Получить [CaseManager](https://github.com/Jodexx/DonateCase/blob/f300a2d2347560ec8e0402a68d512b0ea2da6fa1/api/src/main/java/com/jodexindustries/donatecase/api/DCAPI.java#L65), затем сделать итерацию по данной [хэш мапе](https://github.com/Jodexx/DonateCase/blob/f300a2d2347560ec8e0402a68d512b0ea2da6fa1/api/src/main/java/com/jodexindustries/donatecase/api/manager/CaseManager.java#L34).

После использовать [CaseKeyManager](https://github.com/Jodexx/DonateCase/blob/f300a2d2347560ec8e0402a68d512b0ea2da6fa1/api/src/main/java/com/jodexindustries/donatecase/api/DCAPI.java#L58) для получения ключей от определенного кейса.

**Comment by seven7sas** [comment]
Я понял, спасибо!
